name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Publish
        if: "!github.event.release.prerelease"
        working-directory: ./dist
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc
          npm publish --access public

      - name: Publish release candidate
        if: "github.event.release.prerelease"
        working-directory: ./dist
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc
          npm publish --access public --tag=next