name: Snyk Security Scan
on: push

jobs:
  build:
    name: Test and build
    environment: snyk-npm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Snyk
        run: |
          npm install snyk -g
          npm install snyk-to-html -g
          snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Install dependencies
        run: npm install
      - name: Snyk Open Source
        run: |
          snyk monitor
      - name: Snyk Code
        run: |
          snyk code test || true
      - name: Snyk IaC
        run: |
          snyk iac test || true